name: rilenv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asciitree=0.3.3=py_2
  - black=24.8.0=py38h06a4308_0
  - blosc=1.21.3=h6a678d5_0
  - ca-certificates=2024.9.24=h06a4308_0
  - click=8.1.7=py38h06a4308_0
  - fasteners=0.17.3=pyhd8ed1ab_0
  - flake8=7.1.1=py38h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libblas=3.9.0=24_linux64_openblas
  - libcblas=3.9.0=24_linux64_openblas
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgomp=14.2.0=h77fa898_1
  - liblapack=3.9.0=24_linux64_openblas
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - lz4-c=1.9.4=h6a678d5_1
  - mccabe=0.7.0=pyhd3eb1b0_0
  - msgpack-python=1.0.3=py38h43d8883_1
  - mypy_extensions=1.0.0=py38h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - numcodecs=0.12.1=py38h2c38b39_0
  - openssl=3.3.2=hb9d3cd8_0
  - packaging=24.1=py38h06a4308_0
  - pathspec=0.10.3=py38h06a4308_0
  - pip=24.2=py38h06a4308_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pycodestyle=2.12.1=py38h06a4308_0
  - pyflakes=3.2.0=py38h06a4308_0
  - python=3.8.19=h955ad1f_0
  - python_abi=3.8=2_cp38
  - readline=8.2=h5eee18b_0
  - ruff=0.3.5=py38hab49468_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=py38h06a4308_0
  - typing_extensions=4.12.2=pyha770c72_0
  - wheel=0.44.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zarr=2.17.1=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - addict==2.4.0
      - asttokens==2.4.1
      - attrs==24.2.0
      - backcall==0.2.0
      - blinker==1.8.2
      - build==1.2.2.post1
      - cachetools==5.5.0
      - certifi==2024.8.30
      - cfgv==3.4.0
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - colorama==0.4.6
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.1.1
      - cycler==0.12.1
      - dash==2.18.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - decorator==5.1.1
      - distlib==0.3.8
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastjsonschema==2.20.0
      - filelock==3.16.1
      - flask==3.0.3
      - fonttools==4.54.1
      - fsspec==2024.9.0
      - hidapi==0.14.0.post2
      - identify==2.6.1
      - idna==3.10
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - iniconfig==2.0.0
      - ipython==8.12.3
      - ipywidgets==8.1.5
      - itsdangerous==2.2.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - mypy==1.12.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.1
      - nodeenv==1.9.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.77
      - nvidia-nvtx-cu12==12.1.105
      - open3d==0.18.0
      - opencv-python==4.10.0.84
      - pandas==2.0.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.4.0
      - pip-tools==7.4.1
      - pkgutil-resolve-name==1.3.10
      - plotly==5.24.1
      - pluggy==1.5.0
      - pre-commit==3.5.0
      - prompt-toolkit==3.0.48
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.18.0
      - pyparsing==3.1.4
      - pyproject-api==1.8.0
      - pyproject-hooks==1.2.0
      - pyquaternion==0.9.9
      - pyrealsense2==2.55.1.6486
      - pyserial==3.5
      - pytest==8.3.3
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - referencing==0.35.1
      - requests==2.32.3
      - retrying==1.3.4
      - rpds-py==0.20.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - six==1.16.0
      - spnav==0.9
      - stack-data==0.6.3
      - sympy==1.13.3
      - tenacity==9.0.0
      - threadpoolctl==3.5.0
      - torch==2.4.1
      - torchaudio==2.4.1
      - torchvision==0.19.1
      - tox==4.21.2
      - tqdm==4.66.5
      - traitlets==5.14.3
      - triton==3.0.0
      - tzdata==2024.2
      - urllib3==2.2.3
      - virtualenv==20.26.6
      - wcwidth==0.2.13
      - werkzeug==3.0.4
      - widgetsnbextension==4.0.13
      - xarm-python-sdk==1.14.7
      - zipp==3.20.2
prefix: /home/u-ril/miniconda3/envs/rilenv
